
class RedmineOwner:
    EC_Member = {
        #name = Redmine_user_id
        "Aaron_Chien" : 2048,
        "Aking_Chang" : 2072,
        "AlanHT_Wu" : 1609 ,
        "ArthurOW_Tsai" : 2062,
        "Aryeh_Chen" : 1153,
        "Aster_Wang" : 2052,
        "BarryYM_Li" : 2084,
        "BenKF_Chang": 2050,
        "Block_Chen" : 2049,
        "Changhan_Tsai" :1607,
        "Chewei_Liang" : 1608,
        "Chias_Sung" : 1621,
        "darren_chang" : 1948,
        "Ding_Liu" : 2076,
        "EddieJR_Chen" : 2081,
        "Eddy_Lin" : 2071,
        "elbing_chen" : 2091,
        "EricCY_Tsai" : 1620,
        "EricMT_Tsai" : 2092,
        "Evonne_Chen" : 2055,
        "famous_li" : 2088,
        "Frances_Huang" : 2065,
        "Freddy_Hsu" : 2079,
        "Galvin_Zhu" : 2057,
        "Hank_Shen" : 2061,
        "Hate_Chou" : 2086,
        "HowardCH_Yeh" : 2047,
        "Hsiu_Liu" : 2066,
        "Jaguar_Yu" : 2051,
        "Jake_Wu" : 2070,
        "jaycy_lin" : 2089,
        "Jerry_Jian" : 2064,
        "Jiahuei_Lu" : 2083,
        "Johnson_Fang" : 1623, 
        "Justin_Chi" : 2059, 
        "Ken_Ho" : 2058,
        "Kerr_Lin" : 2085, 
        "Leo_Wang" : 426, 
        "leon_chen" : 2087,
        "LeoYL_Tsai" : 2069,
        "Ling_Lai" : 2056, 
        "Lulumi_Chung" : 1622, 
        "MarsMS_Wu" : 2074,
        "Melvin_Hsiang " : 2078,
        "michaelyc_lin" : 2090,
        "Nick_Shih" : 2073,
        "Peter_Hsieh" : 1606,
        "Reks_Lee" : 2053, 
        "Ruby_Su " : 2080,
        "RyanJC_Yen" : 2054,
        "SamCH_Hsu" : 1644,
        "SeanHY_Shen" : 2067, 
        "Stan_Chiu" : 2082,
        "TommyYD_Huang" : 2075,
        "Tracy_Kuo" : 2077,
        "Vic_Dai" : 1645,
        "WayneWN_Hsu" : 2068,
        "White_Wang" : 2046
    }
    
    BIOS_Member = [ 
    #SW3
    "Bear_Wu", "Justin_Mao","BruceBW_Chen", "devily_chang", "JeffCF_Chen", "Howard_Hung", 
    "Json_Shih","Jean_Hsu", "Boyce_Chiu", "joseph_tu", "Jason_Lee", "minfon_lee", "Leo_Chou", "Ming_Lin",
    "Bruce_Wang", "Alex_Shih", "Kate_Tsao", "JosephYT_Shih", "JoeYC_Chen", "Terry_Su", "Fisher_Yu",
    "BillJW_Liu", "SeanYS_Chang", "MikeHC_Li", "ChrisTY_Lai", "Tim_Shih",
    "Allen_Sung", "JeffCP_Hsu", "KevinPK_Wang", "LilyCH_Huang", "Nowe_Lue", "Kyle_Kuan",
    "Henry_Lee", "DarrenYC_Kuo", "Jin_Lin", "Brandon_Chen", "TinaTY_Chang", "Wen_Wu",
    "Allen_Hu", "Pony_Yang", "Can_Yeh", "Derey_Lin", "Deckard_Chen",
    "KellyPH_Chen", "Tesni_Chen",
    #SW1
    "Joseph_Li", "James_Ting", "Charles_Wang", "Ray_Kao", "Cantor_Chang", "Kenny_Wang",
    "Rita_Lin", "Jeremy_Luo", "James_Liao", "Louis_Shen", "JoeHH_Chung",
    "Terry_Huang", "KING_CHEN", "Lynn_Tsai", "KrisCT_Cheng", "Edison_Yan",
    "AllenCW_Huang", "Henson_Chen", "Ken_Chao", "Andy_Chun", "Harry_Choi",
    "Tenny_Yan", "Willie_Wang", "Ming_Lan", "TimTC_Chen", "Borg_Tseng",
    "CharlesYC_Li", "EricJH_Lin", "Gordon_Wang", "Hao_Chang", "Ming_Chen",
    "AllenHN_Chen", "Jeremy_Li", "Neal_Ni", "Jason_Ke", "Ben_Cheng",
    "EricCY_Peng", "BruceJH_Lin", "KennyKJ_Zhang", "WilliamTW_Huang", "JerryTY_Wang"
    ]